# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check directory
        run: pwd
        shell: cmd

      - name: Check directory 2
        run: pwd
        shell: cmd
        working-directory: ./PAPYRUS
        
      - name: Go to Build directory
        run: cd PAPYRUS
        shell: cmd
        
      - name: Run build scripts
        run: start BUILD.bat
        shell: cmd
